"""add genre and age to user

Revision ID: 445e8fc427c7
Revises: bbe3b5b5db65
Create Date: 2026-05-13 16:49:05.483020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445e8fc427c7'
down_revision = 'bbe3b5b5db65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
