"""add url for contact

Revision ID: a7e9f5d1a2ae
Revises: ca1fb1f4430a
Create Date: 2026-05-14 13:17:45.865633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e9f5d1a2ae'
down_revision = 'ca1fb1f4430a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('insta_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('insta_url')
        batch_op.drop_column('line_url')

    # ### end Alembic commands ###
