"""add early_leave to entries

Revision ID: bbe3b5b5db65
Revises: d9bd5b0a1924
Create Date: 2026-05-12 15:26:32.284793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe3b5b5db65'
down_revision = 'd9bd5b0a1924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('early_leave', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_column('early_leave')

    # ### end Alembic commands ###
