"""add color to groups

Revision ID: fb07031b06db
Revises: 445e8fc427c7
Create Date: 2026-05-14 11:45:02.664530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb07031b06db'
down_revision = '445e8fc427c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
